### ISSUE TITLE
Design Database for User Story 1 + 2

### ISSUE THREAD

**Issue by Buicongbang04** [PiedTeam/NikeCloneTraining-BE-Project#2]

**Comment by quyn2904** [comment]
Table users
_id: ObjectId
username: string
first_name: string
last_name: string
phone_number: hashed string
password: hashed string
email: hashed string
role: enum
   - 0: admin
   - 1: user
created_at: date
updated_at: date
email_otp: string
phone_number_otp: string
status: enum
   - 0: unverified
   - 1: verified
   - 2: banned
avatar_url: string
