### ISSUE TITLE
BE: Register/Login With Mail/FB (US-1)

### ISSUE THREAD

**Issue by Buicongbang04** [PiedTeam/NikeCloneTraining-BE-Project#24]
Description:
Port: 3000

Feature: Google
Path: http://localhost:3000/oauth/google
Method: Get
Enter user information to database
Return: User's profile (username, first_name, last_name, avartar_url, id)

Redirect to route: http://localhost:3000/oauth/google/callback
Method: Get
Take user's profile and put it in request body

Redirect to route: http://localhost:3000/oauth/login-success
Method: Post
Return user's information in database

Feature: Facebook
Path: http://localhost:3000/oauth/facebook
Method: Get
Enter user information to database
Return: User's profile (username, first_name, last_name, avartar_url, id)

Redirect to route: http://localhost:3000/oauth/facebook/callback
Method: Get
Take user's profile and put it in request body

Redirect to route: http://localhost:3000/oauth/login-success
Method: Post
Return user's information in database

**Comment by minhhy2801** [comment]
@quyn2904
