### ISSUE TITLE
BE: Research Login With FB (US-1)

### ISSUE THREAD

**Issue by Buicongbang04** [PiedTeam/NikeCloneTraining-BE-Project#5]

**Comment by Buicongbang04** [comment]
# Title: Feature login with Facebook account

## Authentication process using Facebook
Step 1: From the login page, navigate the user to Facebook's authentication page, ask the user for permission to access personal information and then use it as login information for the user at the login page.

Step 2: Wait for the user to confirm and provide us with permissions to access the user's information.

Step 3: After authorization, Facebook will redirect the user back to our website with information about the access rights the user has allowed.

Step 4: From the information Facebook returns, we will call Facebook's API to get user information such as user name, email...

Step 5: We proceed to create a new account (for new user logging in for the first time) and save new user information into the database; or will proceed to log in the user if the user's information already exists.

## Check a user's login status

First, check to see if the user is logged into Facebook on the device. A call to `FB.getLoginStatus` will trigger a call to Facebook to get the login status. Facebook then calls your callback function with the results.

**Sample code**
```js
FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
});
```

**Response from Facebook as JSON**
```js
{
    status: 'connected',
    authResponse: {
        accessToken: '{access-token}',
        expiresIn:'{unix-timestamp}',
        reauthorize_required_in:'{seconds-until-token-expires}',
        signedRequest:'{signed-parameter}',
        userID:'{user-id}'
    }
}
```
`status` specifies the logged in status of the website. `status` can be one of the following types:
| Type | Description |
|------------------|--------------------------------------------------------------------------------------------------------------------------------|
|`connected` | That user is logged into Facebook and has logged into your website.|
|`not_authorized` | That user is logged into Facebook but not logged into your website.|
|`unknown` | That user is not logged into Facebook, so you don't know if they are logged into your website or not. Or FB.logout() has been called before so it cannot connect to Facebook.|

Nếu trạng thái là `connected`, phản hồi sẽ trả về các thông số `authResponse` sau đây:
| authResponse parameters| Value|
|------------------|--------------------------------------------------------------------------------------------------------------------------------|
|`accessToken` | Website user access code.|
|`expiresIn` | UNIX timestamp when access token expires. After the access token expires, the user needs to log in again.|
|`reauthorize_required_in` | The amount of time before the login session expires (in seconds) and the user needs to log in again.|
|`signedRequest`| A signed parameter contains information about the website user.|
|`userID`| ID of the user.|


## FB.login -> User login
**Sample code** 
```js
FB.login(function(response){
  // handle the response 
});
```
### Request for more permissions
Use the `scope` parameter passed with the `FB.login()` function call. This parameter declares a list of permissions that the user needs to confirm to grant the website access to the user's information.

**Sample code**
```js
FB.login(function(response) {
  // handle the response
}, {scope: 'public_profile,email'});
```

### Handles the Login dialog response
The response (to connect or cancel) will return the `authResponse` object to the callback specified when you called `FB.login()`. This response can be detected and handled in `FB.login()`.
**Sample code**
```js
FB.login(function(response) {
  if (response.status === 'connected') {
    // Logged into your webpage and Facebook.
  } else {
    // The person is not logged into your webpage or we are unable to tell. 
  }
});
```

## FB.logout() -> User logout
**Sample code**
```js
FB.logout(function(response) {
   // Person is now logged out
});
```
**Some special cases need to be noted**
>***Case 1:*** the user has logged in to Facebook and then uses Facebook to log in to the website -> When logging out of the website, he does not log out of Facebook.

>***Case 2:*** the user logs in to Facebook during the login process in the website -> when the user logs out of the web, the user also logs out of Facebook at the same time

>***Case 3:*** The user logs into Facebook from another website, then logs in to your website -> when the user logs out of 1 of the 2 websites, they both log out of Facebook.

**Note**: 
Logging out of a website does not revoke permissions the user has provided. If you want to revoke rights, you must proceed in another step.

**Comment by tientran1234** [comment]
i need library to connect with facebook

**Comment by Buicongbang04** [comment]
> i need library to connect with facebook

In my research, I will use passport-facebook, you can read more here 
https://www.passportjs.org/packages/passport-facebook/
